apiVersion: apps/v1
kind: Deployment
metadata:
  name: eurekaserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eurekaserver
  template:
    metadata:
      labels:
        app: eurekaserver
    spec:
      containers:
        - name: eurekaserver
          image: myapp/eurekaserver:1.0.1

          ports:
            - containerPort: 8761

          env:
            - name: SPRING_APPLICATION_NAME
              value: "eurekaserver"

            - name: OTEL_SERVICE_NAME
              value: "eurekaserver"

#           rabbit mq (common)
            - name: SPRING_RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: global-secret
                  key: RABBITMQ_HOST

#            OPEN TELEMETRY (COMMON)
            - name: JAVA_TOOL_OPTIONS
              valueFrom:
                secretKeyRef:
                  name: global-secret
                  key: OPEN_TEL_JAR_PATH

            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: global-secret
                  key: OTEL_EXPORTER_OTLP_ENDPOINT # Secure password

            - name: OTEL_METRICS_EXPORTER
              valueFrom:
                secretKeyRef:
                  name: global-secret
                  key: OTEL_METRICS_EXPORTER

            - name: OTEL_LOGS_EXPORTER
              valueFrom:
                secretKeyRef:
                  name: global-secret
                  key: OTEL_LOGS_EXPORTER

#           Microservices (Common)
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                secretKeyRef:
                  name: global-secret
                  key: PROFILES_ACTIVE

            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                secretKeyRef:
                  name: global-secret
                  key: SPRING_CONFIG_IMPORT

            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              valueFrom:
                secretKeyRef:
                  name: global-secret
                  key: EUREKA_DEFAULT_ZONE_URL

            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: global-secret
                  key: EUREKA_INSTANCE_PREFER_IP_ADDRESS

            - name: EUREKA_INSTANCE_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: global-secret
                  key: EUREKA_INSTANCE_HOSTNAME

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8761
            initialDelaySeconds: 20
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8761
            initialDelaySeconds: 40
            periodSeconds: 20