apiVersion: apps/v1
kind: Deployment
metadata:
  name: eurekaserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eurekaserver
  template:
    metadata:
      labels:
        app: eurekaserver
    spec:
      containers:
        - name: eurekaserver
          image: myapp/eurekaserver:1.0.1
          ports:
            - containerPort: 8761
          envFrom:
            - configMapRef:
                name: global-config # Load all envs
          env:
            - name: SPRING_APPLICATION_NAME
              value: "eurekaserver"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8761
            initialDelaySeconds: 20