apiVersion: apps/v1
kind: Deployment
metadata:
  name: accountsdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accountsdb
  template:
    metadata:
      labels:
        app: accountsdb
    spec:
      containers:
        - name: mysql
          image: mysql:8.0

          ports:
            - containerPort: 3306

          env:
            - name: MYSQL_DATABASE
              value: "accountsdb"

            # ⚠️ REQUIRED for MySQL to start
            - name: MYSQL_ROOT_PASSWORD
              value: "root"

          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql

          readinessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
            initialDelaySeconds: 20
            periodSeconds: 10

          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
            initialDelaySeconds: 40
            periodSeconds: 20

      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: accountsdb-pvc