apiVersion: v1
kind: Service
metadata:
  name: accountsdb # DNS name inside cluster
spec:
  selector:
    app: accountsdb # Routes traffic to matching pods
  ports:
    - port: 3307 # Cluster port
      targetPort: 3306 # Container port
  clusterIP: None # Headless service (optional for DB)