apiVersion: apps/v1
kind: Deployment
metadata:
  name: loans
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loans
  template:
    metadata:
      labels:
        app: loans
    spec:
      containers:
        - name: loans
          image: myapp/loans:1.0.1

          ports:
            - containerPort: 40003   # 🔁 replace if different

          env:
            - name: SPRING_APPLICATION_NAME
              value: "loans"

            - name: OTEL_SERVICE_NAME
              value: "loans"

            # 🔹 DB Connection
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://loansdb:3306/loansdb"

            - name: SPRING_DATASOURCE_USERNAME
              value: "root"

            - name: SPRING_DATASOURCE_PASSWORD
              value: "root"

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 40003
            initialDelaySeconds: 20
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 40003
            initialDelaySeconds: 40
            periodSeconds: 20