apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  selector:
    app: kafka
  ports:
    - name: external
      port: 8902
      targetPort: 8902

    - name: internal
      port: 29092
      targetPort: 29092

    - name: controller
      port: 29093
      targetPort: 29093

  type: ClusterIP