apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configserver
  template:
    metadata:
      labels:
        app: configserver
    spec:
      containers:
        - name: configserver
          image: myapp/config-server:1.0.1

          ports:
            - containerPort: 8801

          env:
            - name: SPRING_APPLICATION_NAME
              value: "configserver"

            - name: OTEL_SERVICE_NAME
              value: "configserver"

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8801
            initialDelaySeconds: 20
            periodSeconds: 15
            failureThreshold: 5

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8801
            initialDelaySeconds: 40
            periodSeconds: 20