name: rabbitmq

image: rabbitmq:4-management
replicaCount: 1

persistence:
  enabled: true
  name: data
  size: 500Mi
  accessMode: ReadWriteOnce

storage: 500Mi

ports:
  - 5672
  - 15672

env:
  - name: RABBITMQ_NODENAME
    value: "rabbit@localhost"

volumeMounts:
  - name: data
    mountPath: /var/lib/rabbitmq

readinessProbe:
  tcpSocket:
    port: 5672
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3

livenessProbe:
  tcpSocket:
    port: 5672
  initialDelaySeconds: 30
  periodSeconds: 20

service:
  type: ClusterIP
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672

    - name: management
      port: 15672
      targetPort: 15672