services:
  # Infrastructure: RabbitMQ
  rabbit:
    image: rabbitmq:4-management
    hostname: rabbitmq
    ports:
      - "${PORT_RABBIT}:5672"
      - "${PORT_RABBIT_UI}:15672"
    extends:
      file: common-config.yml
      service: network-deploy-service
    volumes:
      - rabbit_data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_port_connectivity" ]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: redis-ms
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 10
    extends:
      file: common-config.yml
      service: network-deploy-service

  postgres:
    image: postgres:15
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U keycloak" ]
      interval: 10s
      timeout: 5s
      retries: 10
    extends:
      file: common-config.yml
      service: network-deploy-service

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak
    command: start-dev
    environment:
      KC_HEALTH_ENABLED: true
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: keycloak
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT: false
    ports:
      - "8911:8080"
    depends_on:
      postgres:
        condition: service_healthy

    healthcheck:
      test: ["CMD-SHELL", "{ printf 'HEAD /health/ready HTTP/1.0\r\n\r\n' >&0; grep '200'; } 0<>/dev/tcp/localhost/8080"]
      interval: 15s
      timeout: 5s
      retries: 10

    extends:
      file: common-config.yml
      service: network-deploy-service


  # Infrastructure: Config Server
  configserver:
    build:
      context: ../../configserver
      dockerfile: Dockerfile
    image: myapp/config-server:1.0.1
    container_name: configserver-ms
    ports:
      - "${PORT_CONFIGSERVER}:${PORT_CONFIGSERVER}"
    depends_on:
      rabbit:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "configserver"
      OTEL_SERVICE_NAME: "configserver"
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:${PORT_CONFIGSERVER}/actuator/health/readiness || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 10
    extends:
      file: common-config.yml
      service: microservice-base-config

  # Databases
  accountsdb:
    container_name: accountsdb
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: accountsdb
    volumes:
      - accountsdb_data:/var/lib/mysql # Maps internal DB storage to a persistent volume
    extends:
      file: common-config.yml
      service: mysql-database-base-config

  cardsdb:
    container_name: cardsdb
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: cardsdb
    volumes:
      - cardsdb_data:/var/lib/mysql
    extends:
      file: common-config.yml
      service: mysql-database-base-config

  loansdb:
    container_name: loansdb
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: loansdb
    volumes:
      - loansdb_data:/var/lib/mysql
    extends:
      file: common-config.yml
      service: mysql-database-base-config

  #Eureka service Registry & discovery
  eurekaserver:
    build:
      context: ../../eurekaserver
      dockerfile: Dockerfile
    image: myapp/eurekaserver:1.0.1
    container_name: eurekaserver
    ports:
      - "${PORT_EUREKASERVER}:${PORT_EUREKASERVER}"
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"
      OTEL_SERVICE_NAME: "eurekaserver"
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:${PORT_EUREKASERVER}/actuator/health/readiness || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  #Gateway Server
  gatewayserver:
    build:
      context: ../../gatewayserver
      dockerfile: Dockerfile
    image: myapp/gatewayserver:1.0.1
    container_name: gatewayserver-ms
    ports:
      - "${PORT_GATEWAYSERVER}:${PORT_GATEWAYSERVER}"
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver: # Ensure Eureka is at least starting
        condition: service_healthy
      redis:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "gatewayserver"
      OTEL_SERVICE_NAME: "gatewayserver"
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: "${OAUTH2_RESOURCESERVER_JWT_ISSUER_URI}"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  # Microservices
  accounts:
    build:
      context: ../../accounts
      dockerfile: Dockerfile
    image: myapp/accounts:1.0.1
    container_name: accounts-ms
    ports:
      - "${PORT_ACCOUNTS}:${PORT_ACCOUNTS}"
    depends_on:
      configserver:
        condition: service_healthy
      accountsdb:
        condition: service_healthy
      eurekaserver: # Ensure Eureka is at least starting
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      OTEL_SERVICE_NAME: "accounts"
      SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:3306/accountsdb"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  cards:
    build:
      context: ../../cards
      dockerfile: Dockerfile
    image: myapp/cards:1.0.1
    container_name: cards-ms
    ports:
      - "${PORT_CARDS}:${PORT_CARDS}"
    depends_on:
      configserver:
        condition: service_healthy
      cardsdb:
        condition: service_healthy
      eurekaserver: # Ensure Eureka is at least starting
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "cards"
      OTEL_SERVICE_NAME: "cards"
      SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3306/cardsdb"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  loans:
    build:
      context: ../../loans
      dockerfile: Dockerfile
    image: myapp/loans:1.0.1
    container_name: loans-ms
    ports:
      - "${PORT_LOANS}:${PORT_LOANS}"
    depends_on:
      configserver:
        condition: service_healthy
      loansdb:
        condition: service_healthy
      eurekaserver: # Ensure Eureka is at least starting
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "loans"
      OTEL_SERVICE_NAME: "loans"
      SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3306/loansdb"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

# NEW: Define the volumes so Docker knows to manage them
volumes:
  accountsdb_data:
  cardsdb_data:
  loansdb_data:
  rabbit_data:
  redis_data:
  keycloak-db-data:

networks:
  observability-net:
    external: true