server:
  port: ${PORT_CARDS:40002}

spring:
  application:
    name: "cards"
  config:
    # Use 'configserver' (the Docker service name) instead of localhost
    import: "optional:configserver:http://configserver:${PORT_CONFIGSERVER:8801}"
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: 5672
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
  datasource:
    # Uses the specific URL passed from docker-compose.yml
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3308/cardsdb}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        # Prevents the metadata extractor from crashing on MySQL
        temp:
          use_jdbc_metadata_defaults: false
        id:
          db_structure_naming_strategy: legacy
        dialect: org.hibernate.dialect.MySQLDialect
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
    kubernetes:
      discovery:
        all-namespaces: true

  sql:
    init:
      mode: always

logging:
  level:
    com:
      eazybytes:
        cards: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true
  metrics:
    logs:
      application: ${spring.application.name}

#eureka:
#  instance:
#    preferIpAddress: true
#  client:
#    fetchRegistry: true
#    registerWithEureka: true
#    serviceUrl:
#      # Use the variable defined in common-config
#      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8070/eureka/}

info:
  app:
    name: "cards"
    description: "Cards application"
    version: "1.0.0"