apiVersion: v1
kind: Service
metadata:
  name: cardsdb # DNS name inside cluster
spec:
  selector:
    app: cardsdb # Routes traffic to matching pods
  ports:
    - port: 3308 # Cluster port
      targetPort: 3306 # Container port
  clusterIP: None # Headless service (optional for DB)