apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_DB
              value: "keycloak"

            - name: POSTGRES_USER
              value: "keycloak"

            - name: POSTGRES_PASSWORD
              value: "keycloak"

          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data

          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - keycloak
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - keycloak
            initialDelaySeconds: 20
            periodSeconds: 15

      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc