apiVersion: apps/v1
kind: Deployment
metadata:
  name: message
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message
  template:
    metadata:
      labels:
        app: message
    spec:
      containers:
        - name: message
          image: myapp/message:1.0.1   # 🔁 update if different

          ports:
            - containerPort: 40004   # 🔁 change if your app uses different port

          env:
            - name: SPRING_APPLICATION_NAME
              value: "message"

            - name: OTEL_SERVICE_NAME
              value: "message"

            # 🔹 Kafka broker
            - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS
              value: "kafka:8902"

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 40004
            initialDelaySeconds: 20
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 40004
            initialDelaySeconds: 40
            periodSeconds: 20