apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatewayserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatewayserver
  template:
    metadata:
      labels:
        app: gatewayserver
    spec:
      containers:
        - name: gatewayserver
          image: myapp/gatewayserver:1.0.1

          ports:
            - containerPort: 8901

          env:
            - name: SPRING_APPLICATION_NAME
              value: "gatewayserver"

            - name: OTEL_SERVICE_NAME
              value: "gatewayserver"

            - name: SPRING_REDIS_HOST
              value: "redis"

            - name: SPRING_REDIS_PORT
              value: "6379"

            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: "http://keycloak:8080/realms/master"

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8901
            initialDelaySeconds: 20
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8901
            initialDelaySeconds: 40
            periodSeconds: 20