apiVersion: 1

datasources:
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    editable: true

    jsonData:
      derivedFields:
        - name: TraceID
          matcherRegex: "\\[(?:[^,]+),([a-f0-9]+),[a-f0-9]+\\]"
          datasourceUid: "tempo"
          url: '${__value.raw}'

        - name: SpanID
          matcherRegex: "\\[(?:[^,]+),[a-f0-9]+,([a-f0-9]+)\\]"
          datasourceUid: "tempo"
          url: '${__value.raw}'