apiVersion: 1
datasources:
  - name: Tempo
    type: tempo
    uid: tempo
    url: http://tempo:3100
    access: proxy
    editable: true

    jsonData:
      serviceMap:
        datasourceUid: 'prometheus'