apiVersion: 1
datasources:
  - name: Tempo
    type: tempo
    uid: tempo
    url: http://tempo:3100
    access: proxy
    editable: true

    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: 'prometheus'
      # Link Tempo traces back to Loki logs using trace_id
      tracesToLogsV2:
        datasourceUid: 'loki'
        spanStartTimeShift: '-1h'
        spanEndTimeShift: '1h'
        filterByTraceID: true
        filterBySpanID: false
        customQuery: true
        query: '{job="docker"} | trace_id = "${__trace.traceId}"'
      # Link Tempo traces to Prometheus metrics
      tracesToMetrics:
        datasourceUid: 'prometheus'
