name: alloy
skipGlobalEnv: true
image: grafana/alloy:v1.7.5
replicaCount: 1

serviceAccountName: alloy

args:
  - run
  - /etc/alloy/config.alloy

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "300m"

service:
  type: ClusterIP
  ports:
    - port: 12345
      targetPort: 12345