apiVersion: v1
kind: List
items:

  # ------------------- SERVICE -------------------
  - apiVersion: v1
    kind: Service
    metadata:
      name: discoveryserver
      labels:
        app: discoveryserver
    spec:
      type: ClusterIP
      selector:
        app: discoveryserver
      ports:
        - name: http
          port: 80
          targetPort: 8761

  # ------------------- SERVICE ACCOUNT -------------------
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: discoveryserver
      labels:
        app: discoveryserver

  # ------------------- ROLE -------------------
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: namespace-reader
      namespace: default
    rules:
      - apiGroups: ["", "extensions", "apps"]
        resources: ["services", "endpoints", "pods"]
        verbs: ["get", "list", "watch"]

  # ------------------- ROLE BINDING -------------------
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: discoveryserver:view
      labels:
        app: discoveryserver
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: namespace-reader
    subjects:
      - kind: ServiceAccount
        name: discoveryserver

  # ------------------- DEPLOYMENT -------------------
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: discoveryserver-deployment
      labels:
        app: discoveryserver
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: discoveryserver
      template:
        metadata:
          labels:
            app: discoveryserver
        spec:
          serviceAccountName: discoveryserver
          containers:
            - name: discoveryserver
              image: springcloud/spring-cloud-kubernetes-discoveryserver:3.2.0
              imagePullPolicy: IfNotPresent

              ports:
                - containerPort: 8761

              readinessProbe:
                httpGet:
                  path: /actuator/health/readiness
                  port: 8761
                initialDelaySeconds: 100
                periodSeconds: 30

              livenessProbe:
                httpGet:
                  path: /actuator/health/liveness
                  port: 8761
                initialDelaySeconds: 100
                periodSeconds: 30