name: accounts
image: myapp/accounts:1.0.1
replicaCount: 1

ports:
  - 40001

# Wait for dependencies (replaces Docker depends_on)
initContainers:
  - name: wait-for-configserver
    image: busybox
    command: ["sh", "-c", "until nc -z configserver 8801; do echo waiting for configserver; sleep 2; done;"]
  - name: wait-for-accountsdb
    image: busybox
    command: ["sh", "-c", "until nc -z accountsdb 3306; do echo waiting for accountsdb; sleep 2; done;"]
#  - name: wait-for-eureka
#    image: busybox
#    command: [ "sh", "-c", "until nc -z eurekaserver 8761; do echo waiting for eureka; sleep 2; done;" ]

env:
  - name: SPRING_APPLICATION_NAME
    value: "accounts"
  - name: OTEL_SERVICE_NAME
    value: "accounts"
  - name: SPRING_DATASOURCE_URL
    value: "jdbc:mysql://accountsdb:3306/accountsdb"
  - name: SPRING_DATASOURCE_USERNAME
    value: "root"
  - name: SPRING_DATASOURCE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: global-secret
        key: MYSQL_ROOT_PASSWORD
  - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS
    value: "kafka:8902"


readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 40001 # Or your internal port, e.g., 40001
  initialDelaySeconds: 50  # Give it nearly a minute
  periodSeconds: 10
  failureThreshold: 5

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 40001
  initialDelaySeconds: 70  # Wait longer than readiness
  periodSeconds: 15

resources:
  requests:
    memory: "300Mi"
    cpu: "200m"
  limits:
    memory: "700Mi"
    cpu: "500m"

service:
  type: ClusterIP
  ports:
    - port: 40001
      targetPort: 40001
