apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configserver
  template:
    metadata:
      labels:
        app: configserver
    spec:
      containers:
        - name: configserver
          image: myapp/config-server:1.0.1

          ports:
            - containerPort: 8801

          env:
            - name: SPRING_APPLICATION_NAME
              value: "configserver"

            - name: OTEL_SERVICE_NAME
              value: "configserver"

#           rabbit mq (common)
            - name: SPRING_RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: RABBITMQ_HOST

#            OPEN TELEMETRY (COMMON)
            - name: JAVA_TOOL_OPTIONS
              valueFrom:
                  configMapKeyRef:
                    name: global-config
                    key: OPEN_TEL_JAR_PATH

            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: OTEL_EXPORTER_OTLP_ENDPOINT # Secure password

            - name: OTEL_METRICS_EXPORTER
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: OTEL_METRICS_EXPORTER

            - name: OTEL_LOGS_EXPORTER
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: OTEL_LOGS_EXPORTER

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8801
            initialDelaySeconds: 20
            periodSeconds: 15
            failureThreshold: 5

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8801
            initialDelaySeconds: 40
            periodSeconds: 20