apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatewayserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatewayserver
  template:
    metadata:
      labels:
        app: gatewayserver
    spec:
      containers:
        - name: gatewayserver
          image: myapp/gatewayserver:1.0.1

          ports:
            - containerPort: 8901

          env:
            - name: SPRING_APPLICATION_NAME
              value: "gatewayserver"

            - name: OTEL_SERVICE_NAME
              value: "gatewayserver"

            - name: SPRING_REDIS_HOST
              value: "redis"

            - name: SPRING_REDIS_PORT
              value: "6379"

            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: "http://keycloak:8080/realms/master"

            #           rabbit mq (common)
            - name: SPRING_RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: RABBITMQ_HOST

            #            OPEN TELEMETRY (COMMON)
            - name: JAVA_TOOL_OPTIONS
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: OPEN_TEL_JAR_PATH

            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: OTEL_EXPORTER_OTLP_ENDPOINT # Secure password

            - name: OTEL_METRICS_EXPORTER
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: OTEL_METRICS_EXPORTER

            - name: OTEL_LOGS_EXPORTER
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: OTEL_LOGS_EXPORTER

            #           Microservices (Common)
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: PROFILES_ACTIVE

            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: SPRING_CONFIG_IMPORT

            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: EUREKA_DEFAULT_ZONE_URL

            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: EUREKA_INSTANCE_PREFER_IP_ADDRESS

            - name: EUREKA_INSTANCE_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: EUREKA_INSTANCE_HOSTNAME

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8901
            initialDelaySeconds: 20
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8901
            initialDelaySeconds: 40
            periodSeconds: 20