apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
data:
  config.alloy: |
    loki.write "default" {
      endpoint {
        url = "http://loki:3100/loki/api/v1/push"
      }
    }

    loki.source.file "containers" {
      targets = [
        {
          "__path__" = "/var/log/containers/*.log"
        }
      ]

      forward_to = [loki.write.default.receiver]
    }