apiVersion: v1
kind: Secret
metadata:
  name: global-secret
type: Opaque # Generic key-value secret
stringData:
  MYSQL_ROOT_PASSWORD: root
  POSTGRES_PASSWORD: keycloak
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: admin