name: postgres

image: postgres:15
storage: 1Gi
persistence:
  enabled: true
  name: data
  size: 500Mi
  accessMode: ReadWriteOnce
ports:
  - 5432

env:
  - name: POSTGRES_DB
    value: keycloak

  - name: POSTGRES_USER
    value: keycloak

  - name: POSTGRES_PASSWORD
    value: keycloak

volumeMounts:
  - name: data
    mountPath: /var/lib/postgresql/data

readinessProbe:
  exec:
    command:
      - sh
      - -c
      - pg_isready -U keycloak
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 10

livenessProbe:
  exec:
    command:
      - sh
      - -c
      - pg_isready -U keycloak
  initialDelaySeconds: 20
  periodSeconds: 10

service:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432